apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::409415949432:role/eksctl-exciting-sculpture-1661096-NodeInstanceRole-CS3ZOMCO94RS
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::409415949432:role/UdacityFlaskDeployCBKubectlRole
      username: build      
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-21T15:54:12Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2073"
  uid: 26342ef4-aef6-4953-8b48-1581571008c4
